# Generated by Django 5.2.9 on 2026-03-12 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_userprofile_xp'),
    ]

    def seed_personas(apps, schema_editor):
        Persona = apps.get_model('chat', 'Persona')
        # Delete Career Coach if it exists
        Persona.objects.filter(name__icontains='Career Coach').delete()
        
        # Create or Update MindMate Persona
        Persona.objects.update_or_create(
            name='MindMate',
            defaults={
                'system_prompt': "You are MindMate, a versatile and intelligent AI assistant. You are designed for general day-to-day chat, similar to ChatGPT. You can help with answering questions, writing, brainstorming, and general conversation. You are empathetic, helpful, and maintain a friendly yet professional tone. You are proficient in both English and Hinglish (Hindi + English). Respond based on the user's language preference.",
                'tone': 'General',
                'is_custom': False
            }
        )

    def revert_personas(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(seed_personas, revert_personas),
    ]
