# Generated by Django 5.2.9 on 2026-03-12 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_seed_mindmate_persona'),
    ]

    def update_mindmate(apps, schema_editor):
        Persona = apps.get_model('chat', 'Persona')
        Persona.objects.filter(name='MindMate').update(
            system_prompt=(
                "You are MindMate, a versatile and intelligent AI assistant for general day-to-day chat. "
                "LANGUAGE RULE: You must match the user's language (English or Hinglish) naturally. "
                "STRICT: Never provide translations of your own words (e.g., skip 'How are you? (Aap kaise ho?)'). "
                "Pick only one language for a single thought and don't repeat yourself."
            )
        )

    operations = [
        migrations.RunPython(update_mindmate),
    ]
