/**
 * Vercel API Client for Clarity CoWork
 * Supports direct file/static deployments, GitHub repo deployments, status checks, and project management.
 */

export interface VercelUser {
  id: string;
  username: string;
  name?: string;
  email?: string;
  avatar?: string;
}

export interface VercelFile {
  file: string;
  data: string;
  encoding?: "utf-8" | "base64";
}

export interface VercelDeploymentResult {
  success: boolean;
  id?: string;
  url?: string;
  name?: string;
  readyState?: "INITIALIZING" | "ANALYZING" | "BUILDING" | "DEPLOYING" | "READY" | "ERROR" | "CANCELED";
  inspectorUrl?: string;
  error?: string;
  createdAt?: number;
  alias?: string[];
}

/**
 * Fetch authenticated Vercel user profile
 */
export async function vercel_get_user(token: string): Promise<VercelUser | null> {
  try {
    const res = await fetch("https://api.vercel.com/v2/user", {
      headers: {
        Authorization: `Bearer ${token.trim()}`,
      },
    });

    if (!res.ok) {
      const err = await res.text();
      console.error("[Vercel API] Failed to fetch user:", res.status, err);
      return null;
    }

    const data = await res.json();
    const user = data.user || data;
    return {
      id: user.id,
      username: user.username || user.email?.split("@")[0] || "vercel_user",
      name: user.name || user.username,
      email: user.email,
      avatar: user.avatar ? `https://vercel.com/api/www/avatar/${user.avatar}?s=160` : undefined,
    };
  } catch (error: any) {
    console.error("[Vercel API Error] vercel_get_user:", error);
    return null;
  }
}

/**
 * Deploy files directly to Vercel (1-Click Instant Static / HTML / React bundle)
 */
export async function vercel_deploy_files(
  token: string,
  projectName: string,
  files: VercelFile[]
): Promise<VercelDeploymentResult> {
  try {
    const cleanName = projectName
      .toLowerCase()
      .replace(/[^a-z0-9-_]/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 52) || `clarity-project-${Date.now().toString(36)}`;

    // Prepare files array for Vercel API
    const formattedFiles = files.map((f) => ({
      file: f.file.replace(/^\/+/, ""),
      data: f.data,
      encoding: f.encoding || "utf-8",
    }));

    // Ensure there is at least an index.html if not provided
    const hasIndex = formattedFiles.some((f) => f.file === "index.html" || f.file === "package.json");
    if (!hasIndex && formattedFiles.length > 0) {
      formattedFiles.push({
        file: "index.html",
        data: `<!DOCTYPE html><html><head><title>${cleanName}</title><meta charset="utf-8"></head><body><h1>${cleanName}</h1><p>Generated by Clarity CoWork</p></body></html>`,
        encoding: "utf-8",
      });
    }

    const payload = {
      name: cleanName,
      files: formattedFiles,
      projectSettings: {
        framework: null,
      },
    };

    const res = await fetch("https://api.vercel.com/v13/deployments", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token.trim()}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(payload),
    });

    const data = await res.json();

    if (!res.ok) {
      console.error("[Vercel API Error] Deploy files failed:", res.status, data);
      return {
        success: false,
        error: data.error?.message || `Deployment failed with status ${res.status}`,
      };
    }

    const hostUrl = data.url ? (data.url.startsWith("http") ? data.url : `https://${data.url}`) : undefined;

    return {
      success: true,
      id: data.id,
      url: hostUrl,
      name: data.name,
      readyState: data.readyState || data.status || "READY",
      inspectorUrl: data.inspectorUrl,
      createdAt: data.createdAt,
      alias: data.alias,
    };
  } catch (error: any) {
    console.error("[Vercel API Error] vercel_deploy_files:", error);
    return {
      success: false,
      error: error.message || "Failed to deploy files to Vercel",
    };
  }
}

/**
 * Deploy a connected GitHub repository to Vercel
 */
export async function vercel_deploy_repo(
  token: string,
  projectName: string,
  gitRepo: string, // e.g. "ShivamSk07/Mindmate"
  branch: string = "main"
): Promise<VercelDeploymentResult> {
  try {
    const cleanName = projectName
      .toLowerCase()
      .replace(/[^a-z0-9-_]/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 52) || `clarity-repo-${Date.now().toString(36)}`;

    // 1. Create or get existing Vercel Project linked to GitHub
    const createProjectRes = await fetch("https://api.vercel.com/v9/projects", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token.trim()}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: cleanName,
        gitRepository: {
          type: "github",
          repo: gitRepo,
        },
      }),
    });

    const projectData = await createProjectRes.json().catch(() => ({}));

    // 2. Trigger deployment on Vercel
    const deployRes = await fetch("https://api.vercel.com/v13/deployments", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token.trim()}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: cleanName,
        gitSource: {
          type: "github",
          repo: gitRepo,
          ref: branch,
        },
      }),
    });

    const deployData = await deployRes.json();

    if (!deployRes.ok) {
      return {
        success: false,
        error: deployData.error?.message || `Vercel repo deployment failed (${deployRes.status})`,
      };
    }

    const hostUrl = deployData.url
      ? deployData.url.startsWith("http")
        ? deployData.url
        : `https://${deployData.url}`
      : undefined;

    return {
      success: true,
      id: deployData.id,
      url: hostUrl,
      name: deployData.name,
      readyState: deployData.readyState || deployData.status || "BUILDING",
      inspectorUrl: deployData.inspectorUrl,
      createdAt: deployData.createdAt,
    };
  } catch (error: any) {
    console.error("[Vercel API Error] vercel_deploy_repo:", error);
    return {
      success: false,
      error: error.message || "Failed to trigger Vercel repo deployment",
    };
  }
}

/**
 * Get deployment status by ID
 */
export async function vercel_get_deployment_status(
  token: string,
  deploymentId: string
): Promise<VercelDeploymentResult> {
  try {
    const res = await fetch(`https://api.vercel.com/v13/deployments/${deploymentId}`, {
      headers: {
        Authorization: `Bearer ${token.trim()}`,
      },
    });

    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      return { success: false, error: err.error?.message || "Failed to fetch deployment status" };
    }

    const data = await res.json();
    const hostUrl = data.url ? (data.url.startsWith("http") ? data.url : `https://${data.url}`) : undefined;

    return {
      success: true,
      id: data.id,
      url: hostUrl,
      name: data.name,
      readyState: data.readyState || data.status,
      inspectorUrl: data.inspectorUrl,
      createdAt: data.createdAt,
    };
  } catch (error: any) {
    return { success: false, error: error.message || "Error checking deployment status" };
  }
}

/**
 * List user's Vercel projects
 */
export async function vercel_list_projects(token: string, limit = 20): Promise<any[]> {
  try {
    const res = await fetch(`https://api.vercel.com/v9/projects?limit=${limit}`, {
      headers: {
        Authorization: `Bearer ${token.trim()}`,
      },
    });

    if (!res.ok) {
      console.error("[Vercel API] Failed to list projects:", res.status);
      return [];
    }
    const data = await res.json();
    return (data.projects || []).map((p: any) => ({
      id: p.id,
      name: p.name,
      framework: p.framework || "other",
      updatedAt: p.updatedAt,
      createdAt: p.createdAt,
      repo: p.link?.repo || null,
      latestDeployments: (p.latestDeployments || []).slice(0, 2),
    }));
  } catch (e: any) {
    console.error("[Vercel API] Error in vercel_list_projects:", e);
    return [];
  }
}

/**
 * List recent deployments
 */
export async function vercel_list_deployments(token: string, limit = 10): Promise<any[]> {
  try {
    const res = await fetch(`https://api.vercel.com/v6/deployments?limit=${limit}`, {
      headers: {
        Authorization: `Bearer ${token.trim()}`,
      },
    });

    if (!res.ok) return [];
    const data = await res.json();
    return (data.deployments || []).map((d: any) => ({
      id: d.uid || d.id,
      name: d.name,
      url: d.url ? `https://${d.url}` : "",
      state: d.state || d.readyState,
      created: d.created,
      target: d.target,
    }));
  } catch {
    return [];
  }
}
